input {
  file {
    path => "/var/logs/lpick/view.log"
    codec => "json"
    start_position => "beginning"   # 파일 처음부터 읽기
    sincedb_path => "/dev/null"     # offset 기억하지 않기 (dev에서는 이게 편함)
  }
}
filter {
  # "message" 필드에 담긴 JSON 문자열을 파싱합니다.
  json {
    source => "message"
  }

  # 파싱이 완료되면 더 이상 필요 없는 원본 "message" 필드를 삭제합니다.
  mutate {
    remove_field => ["message"]
  }
}
output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]     # (5) Elasticsearch 호스트
    index => "lpick-views-%{+YYYY.MM.dd}"  # (6) 집계용 인덱스 (중요!)
  }
}