input {
  file {
    path => "/var/logs/lpick/view.log" # (1) 1단계에서 설정한 로그 파일 경로
    codec => "json"                   # (2) 로그가 JSON 형식이므로 json 코덱 사용
    start_position => "end"           # (3) 파일의 끝에서부터 읽기 시작
  }
}
filter {
  # "message" 필드에 담긴 JSON 문자열을 파싱합니다.
  json {
    source => "message"
  }

  # 파싱이 완료되면 더 이상 필요 없는 원본 "message" 필드를 삭제합니다.
  mutate {
    remove_field => ["message"]
  }
}
output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]     # (5) Elasticsearch 호스트
    index => "lpick-views-%{+YYYY.MM.dd}"  # (6) 집계용 인덱스 (중요!)
  }
}