version: "3.8"

services:

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Seoul # 👈 [추가] Elasticsearch 시간대를 KST로 설정
    command: [ "/bin/bash", "-c", "bin/elasticsearch-plugin install analysis-nori -b && /usr/local/bin/docker-entrypoint.sh" ]
    ulimits:
      memlock: { soft: -1, hard: -1 }
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - C:/logs/lpick:/var/logs/lpick:ro
    environment: # 👈 [추가] Logstash 시간대를 KST로 설정
      - TZ=Asia/Seoul
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5044:5044"

volumes:
  es_data:
    driver: local