spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
