spring:
  config:
    import:
      - optional:classpath:API-KEY.yml
  sql:
    init:
      mode: always   # ← 최초에만 always로 실행, 이후 never로 설정
      schema-locations:
        - classpath:schema.sql   # 스키마(DDL), 테이블 구조
      #data-locations:
      #  - classpath:data.sql     # 초기 데이터(DML), 실제 데이터 기입 sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none